# Generated by Django 5.0 on 2024-01-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_customuser_created_at_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_at',
        ),
    ]
